version: '3.8'

services:
  app:
    image: ${REGISTRY_HOST}:${REGISTRY_PORT}/${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M